### ISSUE TITLE
Flag to use LOCAL/federated_instance data in lieu of -i and -e.

### ISSUE THREAD

**Issue by Jasdemi** [jheidecker/lemmony#18]
It would be great if the script respected local instances allowlist and blocklist and include/exclude automatically during search. 

I'm aware that instances can be included or excluded with -i/-e.

**Comment by jheidecker** [comment]
You mean the federation/defederation list?

**Comment by Jasdemi** [comment]
Yup, the /instances page. I only federate my instance with the ones I whitelisted, so the "-i" command is getting quite long. 

Here is my instances page:
https://lemmy.jasdemi.com/instances

So if it finds any entries under Allowed or Blocked Instances, add them to -i or -e.

**Comment by jheidecker** [comment]
So that info is public and available programmatically also. For example: `curl https://[your-site]/api/v3/federated_instances | jq`

We can create a flag that does include/exclude based on this instead of having to list in command. Does that sound right? 

The logic would be something like:
```
if flag true:
  if allowed is not empty:
    add allowed to include
  if blocked is not empty:
    add blocked to exclude
  else
    do nothing ;the flag shouldn't have been true since the instance doesn't white/blacklist
else
  do nothing
```

**Comment by Jasdemi** [comment]
That sounds exactly right.

**Comment by jheidecker** [comment]
Give me a day or two, unless someone else wants to write it :)

**Comment by jheidecker** [comment]
FYI: This is now default behaviour. No flag necessary. Using the -i or -e options will override this of course.
